// Copyright 2021 Gorbunova Valeria
#ifndef MODULES_TASK_1_GORBUNOVA_V_CONJUGATE_GRADIENT_CONJUGATE_GRADIENT_H_
#define MODULES_TASK_1_GORBUNOVA_V_CONJUGATE_GRADIENT_CONJUGATE_GRADIENT_H_

double conj_grad(double** A, double* B, int S);

#endif  // MODULES_TASK_1_GORBUNOVA_V_CONJUGATE_GRADIENT_CONJUGATE_GRADIENT_H_
